### ISSUE TITLE
Make templates for Code of conduct, contributing and PR template.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#3]
Name them as following:
- CODE_OF_CONDUCT.md 
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md

**Comment by anmolkaur18** [comment]
Please assign this to me. I am interested.

**Comment by navu9999** [comment]
can i work on this?

**Comment by garimasingh128** [comment]
@maze-runnar has already worked on it. So unassigning!

**Comment by oshinsaini** [comment]
please assign this to me

**Comment by oshinsaini** [comment]
Can I make the code of conduct page?

**Comment by oshinsaini** [comment]
Good evening ma'am
I wanted to ask in code of conduct,  I should use profext community or
Student code-in community.

For example:
Diversity and inclusion make the Student Code-in community stronger .

Or
Diversity and inclusion make the profext community stronger .

Because profext is a project and not a community , I have written student
Code-in or  SCI-20.


Please clear my confusion ma'am. Thank you very much.

**Comment by garimasingh128** [comment]
You can use Profext is a part of Student Code in 2020 and during this program, we strive for Diversity and inclusion to make the Student Code-in community stronger. 

You can use Slack channel for further communications.
